pipeline {
    agent any

    tools {
        maven 'maven'   // Make sure "maven" is defined under Global Tool Config
        jdk 'jdk11'     // Likewise for JDK
    }

    environment {
        IMAGE_NAME = "springboot-app"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/Saravana-Pandian-1506/Springboot-Project.git', branch: 'main'
            }
        }

        stage('Build with Maven') {
            steps {
                dir('.') { // This ensures we're in the correct working directory
                    sh 'mvn clean package'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('.') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker run -d -p 8080:8080 $IMAGE_NAME'
            }
        }
    }
}
